# Generated by Django 3.0.8 on 2020-07-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_auto_20200708_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='image',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
